# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["amirminaa@gmail.com"] %>
  email_provider_api_key: <%= ENV["0707googpass"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["575a063a3e2ba8070fd4542f8024891a-us12"] %>
  mailchimp_list_id: <%= ENV["Team"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: abcxyz123

test:
  secret_key_base: abcxyz123

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["amirminaa@gmail.com"] %>
  email_provider_api_key: <%= ENV["0707googpass"] %>
  domain_name: <%= ENV["example.com"] %>
  mailchimp_api_key: <%= ENV["575a063a3e2ba8070fd4542f8024891a-us12"] %>
  mailchimp_list_id: <%= ENV["Team"] %>
  owner_email: <%= ENV["amirminaa@gmail.com"] %>
  secret_key_base: <%= ENV["abcxyz123"] %>
